name: Release + Publish

on:
  push:
    branches:
      - main
    tags:
      - '!*'

jobs:
  release:
    name: "Release + Publish"
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip release') && !contains(github.event.head_commit.message, 'skip ci')"
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CUSTOM_GITHUB_PERSONAL_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

    - name: Check lock file for untrusted packages
      run: npm_config_yes=true npx lockfile-lint --path package-lock.json --allowed-hosts npm --validate-https

    - name: Build package
      run: npm run build

    - name: Check package for packaging errors
      run: npm_config_yes=true npx publint run

    - name: Make a release on NPM and GitHub
      run: npm_config_yes=true npx semantic-release
      env:
        NPM_CONFIG_USERCONFIG: '/dev/null' # Ignore local .npmrc as semantic-release will use ONLY THAT if it finds one, leading to npm auth not working.
        NPM_USERNAME: 'gprasannah'
        NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_PERSONAL_TOKEN }}
        GIT_AUTHOR_NAME: 'GP'
        GIT_AUTHOR_EMAIL: 'GP'
        GIT_COMMITTER_NAME: 'me@httgp.com'
        GIT_COMMITTER_EMAIL: 'me@httgp.com'
